# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sixth Sense' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sixth Sense
  pod 'IKEventSource'

end

target 'Sixth Sense WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sixth Sense WatchKit App

end

target 'Sixth Sense WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sixth Sense WatchKit Extension

end
